### ADD A PLAYER
POST http://localhost:2000/addplayer
Content-Type: application/json

{
"name":"Xhaka"
}

### GET ALL PLAYERS
GET http://localhost:2000/addplayer

### ADD A PLAYER DETAILs
POST http://localhost:2000/detail
Content-Type: application/json

{
"playername":"Xhaka",
"age":25,
"games":100,
"position":9
}

### GET SPECIFIC PLAYER DETAIL
GET http://localhost:2000/detail/Xhaka

### GET ALL PLAYER DETAILs
GET http://localhost:2000/detail